### ISSUE TITLE
[World] Problem with cells and blob's speed

### ISSUE THREAD

**Issue by 3Mydlo3** [Kisu95/GroupProject#10]
If blobs are to move every tick we have a problem of not being able to move blob by non integer number of cells. We need to find a solution to this. Proposed solutions:
- Make cells smaller, so objects take up more than 1 cell. (doesn't solve our issue really)
- Calculate blob move every frame (with previously defined direction) and move him when his move exceeds 1 cell (eg. moves by 0.11 every tick, so real move comes after 10 ticks (10*0.11 > 1).
- Calculate blob's position relative to his cell, so he may be anywhere withing +/- 0.5 from his cell. After crossing +/-0.5 he moves to next cell. This way blobs can move in all directions.

**Comment by Kisu95** [comment]
3rd option, simple and it will work :)
